# Generated by Django 3.2.11 on 2022-01-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('char', '0001_initial'),
        ('srd20', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='class',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.character'),
        ),
        migrations.AddField(
            model_name='class',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srd20.characterclass'),
        ),
        migrations.AddField(
            model_name='characterhealth',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srd20.race'),
        ),
    ]
