# Generated by Django 3.2.11 on 2022-01-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[(1, 'Awful'), (2, 'Shitty'), (3, 'Pretty OK'), (4, 'Good'), (5, 'Great'), (6, 'Awesome'), (7, 'Fucking Majestic')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('item', models.CharField(choices=[(1, 'Rock'), (2, 'Pencil'), (3, 'Knife'), (4, 'Sword'), (5, 'Chainsaw'), (6, 'Machine Gun'), (7, 'Laser')], max_length=1)),
                ('effect', models.CharField(choices=[(1, 'Water'), (2, 'Rock'), (3, 'Fire'), (4, 'Acid'), (5, 'Plasma')], max_length=1)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('char_attack', models.IntegerField()),
                ('char_hp', models.IntegerField()),
                ('char_hp_max', models.IntegerField()),
                ('char_ac', models.IntegerField()),
                ('mon_attack', models.IntegerField()),
                ('mon_hp', models.IntegerField()),
                ('mon_hp_max', models.IntegerField()),
                ('mon_ac', models.IntegerField()),
                ('win', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=255)),
                ('response', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('actor', models.CharField(choices=[(0, 'Hero'), (1, 'Monster')], max_length=1)),
                ('kill', models.BooleanField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.fight')),
            ],
        ),
    ]
