# Generated by Django 3.2.11 on 2022-01-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('char', '0001_initial'),
        ('srd20', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.character'),
        ),
        migrations.AddField(
            model_name='fight',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bonusitem'),
        ),
        migrations.AddField(
            model_name='fight',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srd20.monster'),
        ),
    ]
